version: '3.9'

services:
  api-service:
    container_name: api-container-1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge